- hosts: localhost
  remote_user: ubuntu
  become: true
  tasks:
    - name: ec2 creation
      amazon.aws.ec2_instance:
        key_name: network.pem
        instance_type: t2.micro
        image_id: ami-0522ab6e1ddcc7055
        region: "ap-south-1"
        count: 1
        vpc_subnet_id: subnet-098a407db67b7a105
        network:
          assign_public_ip: yes
    

