---
- hosts: all
  become: true
  vars:
    ports: 9090
  tasks:

    - name: Update apt package manager
      apt:
        update_cache: yes

    - name: Install dependencies for Jenkins
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-11-jdk
        - gnupg2
        - ca-certificates

    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins repository to sources list
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Ensure Jenkins listens on port {{ ports }}
      ansible.builtin.lineinfile:
        path: /etc/default/jenkins
        regexp: '^HTTP_PORT='
        line: HTTP_PORT={{ ports }}
      notify: restart Jenkins

    - name: Ensure Jenkins is started and enabled on boot
      systemd:
        name: jenkins
        state: started
        enabled: true

  handlers:
    - name: restart Jenkins
      systemd:
        name: jenkins
        state: restarted
