---
- hosts: all
  remote_user: ubuntu
  become: true
  tasks:
    - name: Install apache httpd
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Copy file with owner and permissions
      copy:
        src: index.html
        dest: /var/www/html
        mode: '0644'
